//DECKFIELD FUNCTIONALITY
export const ADD_DECK = 'ADD_DECK'
export const REMOVE_DECK = 'REMOVE_DECK'
export const SELECT_DECK = 'SELECT_DECK'
export const SAVE_DECK = 'SAVE_DECK'
export const POPULATE_DECKS = 'POPULATE_DECKS'
export const SAVE_TO_LOCAL = 'SAVE_TO_LOCAL'
export const CLEAR_DECKS = 'CLEAR_DECKS'

//MATCHUP FUNCTIONALITY
export const ADD_MATCHUP = 'ADD_MATCHUP'
export const REMOVE_MATCHUP = 'REMOVE_MATCHUP'
export const SORT_MATCHUP = 'SORT_MATCHUP'
export const CLEAR_MATCHUPS = 'CLEAR_MATCHUPS'

//MSG FUNCTIONALITY
export const INFO_MSG = 'INFO_MSG'
export const ERROR_MSG = 'ERROR_MSG'
