//DECKFIELD FUNCTIONALITY
export const ADD_DECKCARD = 'ADD_DECKCARD'
export const REMOVE_DECKCARD = 'REMOVE_DECKCARD'
export const SELECT_DECKCARD = 'SELECT_DECKCARD'
export const POPULATE_DECKS = 'POPULATE_DECKS'
export const SAVE_TO_LOCAL = 'SAVE_TO_LOCAL'
